const test = require('node:test');
const assert = require('node:assert/strict');
const Sequelize = require('sequelize');
const migration = require('../migrations/20260908000001-create-google-play-review-accounts');

// Opt in with REVIEW_MIGRATION_TEST_ENV=development (or test).
// All writes use connection-local temporary tables and are rolled back.
const environment = process.env.REVIEW_MIGRATION_TEST_ENV;
test('review accounts support a ViewerStyles join table without an id column', {
    skip: !environment,
}, async () => {
    assert.ok(['development', 'test'].includes(environment), 'Use a non-production database');
    const config = require('../config/config')[environment];
    const db = new Sequelize({ ...config, logging: false });
    let transaction;
    try {
        transaction = await db.transaction();
        const query = (sql, options = {}) => db.query(sql, { ...options, transaction });
        for (const table of ['Publishers', 'Viewers', 'Styles', 'PublisherSettings']) {
            await query(`CREATE TEMP TABLE "${table}" (LIKE public."${table}" INCLUDING DEFAULTS) ON COMMIT DROP`);
            // Independent temporary sequences prevent touching real account sequences.
            await query(`ALTER TABLE pg_temp."${table}" ALTER COLUMN id DROP DEFAULT`);
            await query(`ALTER TABLE pg_temp."${table}" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`);
        }
        await query(`CREATE TEMP TABLE "ViewerStyles" (
            "viewerId" INTEGER NOT NULL, "styleId" INTEGER NOT NULL,
            "createdAt" TIMESTAMPTZ NOT NULL, "updatedAt" TIMESTAMPTZ NOT NULL,
            PRIMARY KEY ("viewerId", "styleId")
        ) ON COMMIT DROP`);
        await query(`INSERT INTO pg_temp."Styles" (name, "createdAt", "updatedAt")
            VALUES ('Review test style', NOW(), NOW())`);
        const qi = db.getQueryInterface();
        const isolatedInterface = {
            sequelize: { query: db.query.bind(db), transaction: callback => callback(transaction) },
            bulkInsert: qi.bulkInsert.bind(qi),
        };
        await migration.up(isolatedInterface, Sequelize);
        const snapshot = async () => {
            const result = {};
            for (const table of ['Publishers', 'Viewers', 'PublisherSettings', 'ViewerStyles']) {
                result[table] = await query(`SELECT * FROM pg_temp."${table}"`, {
                    type: Sequelize.QueryTypes.SELECT,
                });
                assert.equal(result[table].length, 1, `${table} should have one review row`);
            }
            return result;
        };
        const first = await snapshot();
        assert.equal(first.Publishers[0].isEmailVerified, true);
        assert.equal(first.Publishers[0].accountSetupComplete, true);
        assert.equal(first.Viewers[0].isVerified, true);
        assert.equal(first.Viewers[0].setupCompleted, true);
        assert.equal(first.ViewerStyles[0].viewerId, first.Viewers[0].id);
        await migration.up(isolatedInterface, Sequelize);
        assert.deepEqual(await snapshot(), first, 'Reruns preserve the accounts and preferences');
    } finally {
        if (transaction) await transaction.rollback();
        await db.close();
    }
});
